name: Testar servidor Node.js

on:
  push:
    branches:
      - main  # Aciona o workflow quando houver um push na branch 'main'

jobs:
  build_and_run:
    runs-on: ubuntu-latest  # Executa o job em uma máquina virtual com Ubuntu

    steps:
      # Passo 1: Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # Passo 2: Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  

      # Passo 3: Instalar as dependências
      - name: Instalar dependências
        run: npm install

      # Passo 4: Rodar o servidor
      - name: Rodar o servidor
        run: |
          nohup node app.js &
          echo "Servidor rodando em segundo plano..."

      # Passo 5: Testar se o servidor está funcionando com curl
      - name: Testar se o servidor está funcionando
        run: |
          sleep 10  # Espera o servidor iniciar
          curl http://localhost:3000  # Verifica se o servidor responde

      # Passo 6: Enviar e-mail após conclusão
      - name: Enviar e-mail de conclusão
        if: always()  # Executa este passo independente do sucesso ou falha dos passos anteriores
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Configurar com o servidor SMTP
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}  # Nome de usuário configurado no GitHub Secrets
          password: ${{ secrets.SMTP_PASSWORD }}  # Senha configurada no GitHub Secrets
          subject: "Workflow de Teste do Servidor Node.js Concluído"
          to: marcosdonarumo@gmail.com  # E-mail para onde será enviado o alerta
          from: noreply@exemplo.com  # E-mail de origem
          body: |
            O workflow 'Testar servidor Node.js' foi concluído.
            Status: ${{ job.status }}.
            Verifique o GitHub Actions para mais detalhes.
